displayName=Custom Game Tabs
author=Freddy
description=Move, resize, arrange, and style Resizable Modern game tabs.
tags=tabs,interface,ui,movable,customizable
version=1.0.0
plugins=com.freddy.verticaltabs.VerticalTabsPlugin
build=standard
