displayName=Custom Game Tabs
author=Freddy
description=Move, resize, arrange, and style Resizable Modern game tabs.
tags=tabs,interface,ui,movable,customizable
version=2.2.2
plugins=com.freddy.customgametabs.CustomGameTabsPlugin
build=standard
